apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext1987
  labels:
    app: BoundedContext1987
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext1987
  template:
    metadata:
      labels:
        app: BoundedContext1987
    spec:
      containers:
        - name: BoundedContext1987
          image: "username/BoundedContext1987:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
